Repository diversiwaver/aFRR-NET, pull requests merged in 2023-01, with the labels that each got.

#131 Update SignalDTO to contain a list of assets to regulate
  aFRR-Service/DtoConverters/AssetDTO.cs
  aFRR-Service/DtoConverters/BidDTO.cs
  aFRR-Service/DtoConverters/DTOConverters/DTOConverter.cs
  aFRR-Service/DtoConverters/SignalDTO.cs
  aFRR-Service/TestWebAPI/Tests/TestBidController.cs
  aFRR-Service/TestWebAPI/Tests/TestSignalController.cs
  aFRR-Service/WebAPI/Controllers/BidsController.cs
  aFRR-Service/WebAPI/Controllers/SignalsController.cs
Labels: enhancement

#129 91 implement afrr service message consumer
  .gitignore
  aFRR-Service/MessageConsumer/Class1.cs
  aFRR-Service/MessageConsumer/Consumers/TsoSignalConsumer.cs
  aFRR-Service/MessageConsumer/MessageConsumer.csproj
  aFRR-Service/MessageConsumer/Program.cs
  aFRR-Service/MessageConsumer/Properties/launchSettings.json
  aFRR-Service/MessageConsumer/appsettings.Development.json
  aFRR-Service/MessageConsumer/appsettings.json
  aFRR-Service/WebAPI/Properties/launchSettings.json
  aFRR-Service/WebAPI/WebAPI.csproj
  aFRR-Service/aFRR-Service.sln
Labels: feature

#142 Connecting all the layers
  aFRR-Service/MessageConsumer/Consumers/TsoSignalConsumer.cs
  aFRR-Service/MessageConsumer/Program.cs
  aFRR-Service/MessageConsumer/appsettings.json
Labels: feature

#140 Integration test for Web API
  aFRR-Service/TestWebAPI/Configuration.cs
  aFRR-Service/TestWebAPI/IntegrationTestaFFRService.cs
Labels: test
